export const ActionTypes={
  GET_TOKEN:'GET_TOKEN',
  GET_TOKEN_FAIL:'GET_TOKEN_FAIL',
  GET_TOKEN_SUCCESS:'GET_TOKEN_SUCCESS',

  REFRESH_TOKEN: 'REFRESH_TOKEN',
  REFRESH_TOKEN_FAIL: 'REFRESH_TOKEN_FAIL',
  REFRESH_TOKEN_SUCCESS: 'REFRESH_TOKEN_SUCCESS',

  LOGIN:'LOGIN',
  LOGIN_FAIL:'LOGIN_FAIL',
  LOGIN_SUCCESS:'LOGIN_SUCCESS',

  LOGOUT:'LOGOUT',

  // user정보 수정
  USER_EDIT:'USER_EDIT',
  USER_EDIT_SUCCESS:'USER_EDIT_SUCCESS',
  USER_EDIT_FAIL:'USER_EDIT_FAIL',


  GET_USERME:'GET_USERME',
  GET_USERME_SUCCESS:'GET_USERME_SUCCESS',


  ////////////////////////////////////////////////////////////
  /// faq 관련
  LOAD_FREQUENTLYASKEDBOARD:'LOAD_FREQUENTLYASKEDBOARD',
  LOAD_FREQUENTLYASKEDBOARD_SUCCESS:'LOAD_FREQUENTLYASKEDBOARD_SUCCESS',
  LOAD_FREQUENTLYASKEDBOARD_FAIL:'LOAD_FREQUENTLYASKEDBOARD_FAIL',
  

  ////////////////////////////////////////////////////////////
  /// noticeBoard 관련
  LOAD_NOTICEBOARD:'LOAD_NOTICEBOARD',
  LOAD_NOTICEBOARD_SUCCESS:'LOAD_NOTICEBOARD_SUCCESS',
  LOAD_NOTICEBOARD_FAIL:'LOAD_NOTICEBOARD_FAIL',


  //QnABoard 관련 
  LOAD_QNABOARDLIST:'LOAD_QNABOARDLIST',
  LOAD_QNABOARDLIST_SUCCESS:'LOAD_QNABOARDLIST_SUCCESS'
}